### ISSUE TITLE
 Regular Expression Matching

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#10]
## Leetcode Question no. - 10

**Problem name** -  Regular Expression Matching

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kapshar** [comment]
Hey @pawangeek, can I work on this issue.

**Comment by pawangeek** [comment]
Sure do it, add folder with number '0010'

**Comment by kapshar** [comment]
Can you help me, when I do git push it shows an error  " remote: Permission to python-geeks/Leetcode-scripts.git denied to kapshar."
