### ISSUE TITLE
21 | Merge Two Sorted Lists | Python

### ISSUE THREAD

**Issue by suburban-daredevil** [python-geeks/Leetcode-scripts#19]
## Leetcode Question no. - 21

**Problem name** - Merge Two Sorted Lists

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by suburban-daredevil** [comment]
Hey @pawangeek . I would like to contribute. Can you assign this issue to me?

**Comment by Hussain6** [comment]
Can you assign this to me?
