### ISSUE TITLE
Roman to Integer

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#25]
## Leetcode Question no. - 13

**Problem name** - Roman to Integer

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by KanhaKorgaonkar** [comment]
Hi! I would like to take up this issue please. Thanks!

**Comment by KanhaKorgaonkar** [comment]
Hey @pawangeek Have made a PR, please check. Thanks!

**Comment by pawangeek** [comment]
@KanhaKorgaonkar fix the linting

**Comment by KanhaKorgaonkar** [comment]
I did now, thanks for the feedback. Could you please check again? Thank you!

**Comment by KanhaKorgaonkar** [comment]
@pawangeek I’d like you to review the PR please. Thank you!
