### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#3]
## Leetcode Question no. - 3

**Problem name** - Longest Substring Without Repeating Characters

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by SaulPuente** [comment]
Hi, can you assign this to me?
