### ISSUE TITLE
 Remove Nth Node From End of List

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#31]
## Leetcode Question no. - 19

**Problem name** -  Remove Nth Node From End of List

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by namitaarya** [comment]
Can I take this up?
