### ISSUE TITLE
29 | Divide Two Integers | Python

### ISSUE THREAD

**Issue by SOURAB-BAPPA** [python-geeks/Leetcode-scripts#37]
## Leetcode Question no. -29

**Problem name** -Divide Two Integers

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by SOURAB-BAPPA** [comment]
please assign me to solve this problem

**Comment by Manas146** [comment]
Can I work on this issue please?

**Comment by SOURAB-BAPPA** [comment]
@pawangeek please assign this problem to me so I start solving this
