### ISSUE TITLE
66 | Plus One | Python

### ISSUE THREAD

**Issue by Mansi-Binjola** [python-geeks/Leetcode-scripts#39]
## Leetcode Question no. - 66

**Problem name** - Plus One

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Mansi-Binjola** [comment]
I would like to contribute to this issue. Kindly assign it to me.

**Comment by Manas146** [comment]
Can I work on this issue please?
I did one yesterday as well.
