### ISSUE TITLE
 Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#4]
## Leetcode Question no. - 4

**Problem name** -  Median of Two Sorted Arrays

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by thevirtualbuddy** [comment]
Hi again @pawangeek, 
Can I take up this issue? :)
