### ISSUE TITLE
23 | Merge k Sorted Lists | Python

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#42]
## Leetcode Question no. - 23

**Problem name** - Merge k Sorted Lists

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by atharvabhatt200** [comment]
Hello @pawangeek, can you please assign me this question?
