### ISSUE TITLE
25 | Reverse Nodes in k-Group | Pythpn

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#44]
## Leetcode Question no. - 25

**Problem name** - Reverse Nodes in k-Group

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by SOURAB-BAPPA** [comment]
@pawangeek i want to solve this problem
