### ISSUE TITLE
26 | Remove Duplicates from Sorted Array | Python

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#45]
## Leetcode Question no. - 26

**Problem name** - Remove Duplicates from Sorted Array

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by rushil180101** [comment]
Hello, I would like to work on this issue.
