### ISSUE TITLE
27 | Remove Element | Python

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#46]
## Leetcode Question no. - 27

**Problem name** - Remove Element

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ankitramtriya** [comment]
I want to solve this

**Comment by allwells** [comment]
@pawangeek 
It's been 7 days already and this issue has not been submitted yet.
I don't know if he's still on it.
I want to solve it.
