### ISSUE TITLE
31 |  Next Permutation | Python

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#48]
## Leetcode Question no. - 31

**Problem name** -  Next Permutation

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by SOURAB-BAPPA** [comment]
i want to solve this
