### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Leetcode-scripts#5]
## Leetcode Question no. - 5

**Problem name** - Longest Palindromic Substring

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by krishnak3101** [comment]
Hi, Could you assign this to me?

**Comment by ShivamChoudhary17** [comment]
Hi!
I would like to add Longest Palindromic Substring
Could you please assign this issue to me?
Thank You!
