### ISSUE TITLE
Adding solution of problem no. 0204

### ISSUE THREAD

**Issue by Hemant1101** [python-geeks/Leetcode-scripts#78]
## Leetcode Question no. - 0204

**Problem name** - Count Primes

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by sai-sri-nandan** [comment]
Hey.. I would like to work on this. Can you assign this to me?

**Comment by Hemant1101** [comment]
I have created this issue and want to submit the solution , can you assign it to me. This is my first time making any PR so sorry in advance for any mistakes.
