### ISSUE TITLE
374 | Guess number higher or lower | Python

### ISSUE THREAD

**Issue by suburban-daredevil** [python-geeks/Leetcode-scripts#83]
## Leetcode Question no. - 374

**Problem name** - Guess number higher or lower

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by suburban-daredevil** [comment]
Hey @pawangeek . I would like to contribute. Can you assign this issue to me?

**Comment by thevectorguy** [comment]
hey @pawangeek can you assign this issue to me I'm a beginner and I haven't been able to start my 1st pr

**Comment by SanjanaSogimatt** [comment]
Can I work on this?
