### ISSUE TITLE
31. | Roman To Integer | Python

### ISSUE THREAD

**Issue by Ishika2** [python-geeks/Leetcode-scripts#85]
## Leetcode Question no. - 31.

**Problem name** - Roman To Integer

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment]
@Ishika2 Duplicate of #34
